=begin

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

=end

def pentagonal_list
  @pent_array = []
  (1..3000).each do |i|
    pent = i * ((3 * i) - 1) / 2
    @pent_array << pent
  end
end

def pent_sum_diff
  pentagonal_list
   @pent_array.combination(2) do |ary|
    sum = ary[0] + ary[1]
    diff = ary[1] - ary[0]
    print diff if @pent_array.include?(sum) && @pent_array.include?(diff)
  end
end

pent_sum_diff